name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: selenium/standalone-firefox:latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium bs4 jq

      - name: Load environment variables
        run: |
          echo "WSJ_USERNAME=$WSJ_USERNAME" >> .env
          echo "WSJ_PASSWORD=$WSJ_PASSWORD" >> .env

      - name: Test with unittest
        env:
          WSJ_USERNAME: ${{ secrets.WSJ_USERNAME }}
          WSJ_PASSWORD: ${{ secrets.WSJ_PASSWORD }}
        run: |
          python -m unittest 
